name: Deploy API to EC2 staging

on:
  push:
    branches:
      - main

jobs:
  fetch-vars:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      api_service_name: ${{ vars.API_SERVICE_NAME }}
      api_service_path: ${{ vars.API_SERVICE_PATH }}
    steps:
      - run: |
          echo "Exposing ENV vars to reusable workflows."

  deploy:
    needs: fetch-vars
    uses: ./.github/workflows/deploy-dotnet-service-ec2.yml
    secrets: inherit
    with:
      project-name: Api
      dotnet-version: '6.0.x'
      service-name: ${{ needs.fetch-vars.outputs.api_service_name }}
      service-path: ${{ needs.fetch-vars.outputs.api_service_path }}
