name: Deploy API to EC2 staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-dotnet-service-ec2.yml
    secrets: inherit
    with:
      project-name: Api
      dotnet-version: '6.0.x'
      service-name: ${{ vars.API_SERVICE_NAME }}
      service-path: ${{ vars.API_SERVICE_PATH }}