name: Deploy API to EC2 staging

on:
  push:
    branches:
      - main

jobs:
  fetch-vars:
    runs-on: ubuntu-latest
    environment: staging
    outputs:
      api_service_name: ${{ steps.set-vars.outputs.api_service_name }}
      api_service_path: ${{ steps.set-vars.outputs.api_service_path }}
    steps:
      - name: Set Environment Variables
        id: set-vars
        run: |
          echo "api_service_name=${{ vars.API_SERVICE_NAME }}" >> $GITHUB_OUTPUT
          echo "api_service_path=${{ vars.API_SERVICE_PATH }}" >> $GITHUB_OUTPUT

  deploy:
    needs: fetch-vars
    uses: ./.github/workflows/deploy-dotnet-service-ec2.yml
    secrets: inherit
    with:
      project-name: Api
      dotnet-version: '6.0.x'
      service-name: ${{ needs.fetch-vars.outputs.api_service_name }}
      service-path: ${{ needs.fetch-vars.outputs.api_service_path }}
