name: Deploy Website to EC2 staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy-dotnet-service-ec2.yml
    secrets: inherit
    with:
      project-name: Website
      dotnet-version: '8.0.x'
      service-name: ${{ env.WEBSITE_SERVICE_NAME }}
      service-path: ${{ env.WEBSITE_SERVICE_PATH }}
