version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
      - "5004:5004"  # Port for debugger
    volumes:
      - .:/src
    command: ["dotnet", "watch", "run"]

  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:8080"
      - "5005:5005"  # Port for debugger
    volumes:
      - .:/src
    command: ["dotnet", "watch", "run"]
